### ISSUE TITLE
Create a client from Windows

### ISSUE THREAD

**Issue by coltiebaby** [coltiebaby/bastion#2]
Currently we can only get the client from a unix platform. Lets get the information from windows if possible.

**Comment by turtletowerz** [comment]
Figured i'd leave a comment about one way to do this. Running the following command in the Windows command prompt while the League Client is open will display the Command Line information of the client, allowing you to grab the port and token.

`wmic process where name="LeagueClientUx.exe" get Caption,Processid,Commandline`

If you grab the output of this and regex in the same way that you do with unix systems, all the necessary information can be grabbed in almost the exact same way. Read more about WMI [here](https://docs.microsoft.com/en-us/windows/win32/wmisdk/wmi-start-page). Hope this helps a bit!

**Comment by coltiebaby** [comment]
I'll check it out @turtletowerz. Appreciate it.
